language: ruby
rvm:
  - 1.9.3
gemfile: Gemfile
script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
