development:
      host: localhost
      adapter: mysql2
      database: wave_crm_development
      port: 3306
      username: root
      password:

test: &test
      host: localhost
      adapter: mysql2
      database: wave_crm_test
      port: 3306
      username: root
      password:

production:
      host: localhost
      adapter: mysql2
      database: wave_crm_production
      port: 3306
      username: root
      password:
cucumber:
  <<: *test
