# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0319ad10f2a5e66ee5f95105431fd6c39ac66a8f15092293f9661449a98822716314a7a4c02e739c3f9f08279f6e7d8a68f1f331eacf8ae230e754b5051dce8e

test:
  secret_key_base: a62136d0601589f95e4146222b2e7d3010720e4454c070123ceb2fd8468ccdf50976ee0e3b18c2c31de08cd4fb6c0fce727e0c149ebe34d129c525162ca14580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
